# Generated by Django 5.2 on 2025-05-20 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_user_alter_expense_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Rate per unit', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('EUR', '€ Euro'), ('USD', '$ Dollar')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
