# Generated by Django 6.0.2 on 2026-03-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_rate_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='expenses.category')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.subcategory'),
        ),
    ]
