version: '3.8'

services:
  db_test:
    image: postgres:15-alpine
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password

  redis_test:
    image: redis:7-alpine

  frontend_test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend_test:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend_test

  backend_test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pytest --maxfail=1 --disable-warnings
    env_file:
      - ./.env.dev
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SETTINGS_MODULE: backend.settings
      DATABASE_URL: postgres://postgres:postgres_password@db_test:5432/test_db
      CELERY_BROKER_URL: redis://redis_test:6379/0
      FRONTEND_URL: http://frontend_test:5173
    depends_on:
      - db_test
      - redis_test