services:
  db:
    image: postgres:15-alpine
    container_name: eta_db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_network

  redis:
    image: redis:7-alpine
    container_name: eta_redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - internal_network

  backend:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_backend
    restart: always
    env_file:
      - .env
    volumes:
      - staticfiles:/app/staticfiles
      - media_data:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network
      - web_network

  celery_worker:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_celery_worker
    restart: always
    command: celery -A backend worker --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network

  celery_beat:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_celery_beat
    restart: always
    command: celery -A backend beat --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_network

  frontend:
    image: ghcr.io/kiyayenzire/eta_frontend:latest
    container_name: eta_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - web_network

networks:
  internal_network:
    driver: bridge
  web_network:
    external: true

volumes:
  db_data:
  redis_data:
  staticfiles:
  media_data: