services:
  db:
    image: postgres:15-alpine
    container_name: eta_db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: eta_redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  migration:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_migration
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_initial_data"
    env_file:
      - .env
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_backend
    restart: always
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  celery_worker:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_celery_worker
    restart: always
    command: celery -A backend worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  celery_beat:
    image: ghcr.io/kiyayenzire/eta_backend:latest
    container_name: eta_celery_beat
    restart: always
    command: celery -A backend beat --loglevel=info -S django_celery_beat.schedulers:DatabaseScheduler --pidfile=/tmp/celerybeat.pid
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  frontend:
    image: ghcr.io/kiyayenzire/eta_frontend:latest
    container_name: eta_frontend
    restart: always
    ports:
      - "127.0.0.1:3002:5173"
    depends_on:
      - backend

volumes:
  db_data:
  redis_data: