# Generated by Django 4.2.29 on 2026-08-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='account_deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
