# Generated by Django 4.2.29 on 2026-09-01 11:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, help_text='Optional profile photo for the account.', null=True, upload_to=accounts.models.user_profile_picture_upload_path),
        ),
    ]
