# Generated by Django 4.2.29 on 2026-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_item_measurement_expenseentry_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='amount_base_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='applied_rate_to_eur',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
