# Generated by Django 4.2.29 on 2026-09-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_currencyrate_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='measurement',
            field=models.CharField(choices=[('br', 'Bar(br)'), ('bt', 'Bottle (bt)'), ('bx', 'Box (bx)'), ('ct', 'Carton (ct)'), ('kg', 'Kilogram (kg)'), ('ltr', 'Litre (ltr)'), ('mth', 'Month (mth)'), ('pc', 'Piece (pc)'), ('pk', 'Package (pk)'), ('pr', 'Pair (pr)'), ('tn', 'Tin (tn)'), ('un', 'Unit (un)'), ('yr', 'Year (yr)')], default='pc', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='measurement',
            field=models.CharField(choices=[('br', 'Bar(br)'), ('bt', 'Bottle (bt)'), ('bx', 'Box (bx)'), ('ct', 'Carton (ct)'), ('kg', 'Kilogram (kg)'), ('ltr', 'Litre (ltr)'), ('mth', 'Month (mth)'), ('pc', 'Piece (pc)'), ('pk', 'Package (pk)'), ('pr', 'Pair (pr)'), ('tn', 'Tin (tn)'), ('un', 'Unit (un)'), ('yr', 'Year (yr)')], default='pc', max_length=3),
        ),
    ]
